# This is the Config for this bot

# Insert your bot token here
token: null

maindiscordguild: -1

debugmode: true

ownerids:
   - 801856678063898644

mysql:
   enabled: false
   hostname: null
   port: null
   username: null
   password: null
   database: null
   