{
	"bottoken" : "INSERT TOKEN",
	"debugmode" : true,
	"defaultprefix" : "m!",
    "allowslashcommands" : true,
    "autoupdate" : true,
    "ratelimitmaxrequests" : 3,
    "ratelimititerationduration" : 5000
}